### ISSUE TITLE
SSL certificate, error.

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#109]
Hello,

I wanted to use port 80, and put an SSL certificate on port 443.

Here's how I modified the file ocker-compose.yml:

```
version: '3.9'

services:
  dialoqbase:
    image: n4z3m/dialoqbase:latest
    container_name: dialoqbase
    restart: unless-stopped
    ports:
      - 80:3000
      - 443:443
    environment:
      DATABASE_URL: postgres://postgres:postgres@dialoqbase-pg:5432/dialoqbase?connection_limit=15&pool_timeout=0
      DB_REDIS_URL: redis://redis:6379
    env_file:
      - .env
    depends_on:
      - dialoqbase-pg
      - redis
    volumes:
      - .uploads:/app/uploads
      - ./letsencrypt:/etc/letsencrypt
      - ./lib/letsencrypt:/var/lib/letsencrypt

  dialoqbase-pg:
    image: ankane/pgvector:latest
    container_name: dialoqbase-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dialoqbase
    volumes:
      - .postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - .redis:/data

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
```
Then I ran the following commands:

`docker-compose down`
`docker run -it --rm --name certbot -v "$(pwd)/letsencrypt:/etc/letsencrypt" -v "$(pwd)/lib/letsencrypt:/var/lib/letsencrypt" -p 80:80 certbot/certbot certonly --standalone -d bot.hd1.ch --email your-comeback01@gmail.com --agree-tos --no-eff-email`
`docker-compose up -d`

**docker logs dialoqbase**
```
yarn run v1.22.19
$ npx prisma migrate deploy && fastify start  app.js
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "dialoqbase", schema "public" at "dialoqbase-pg:5432"

14 migrations found in prisma/migrations


No pending migrations to apply.
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.2.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
npm notice Run `npm install -g npm@10.2.0` to update!
npm notice
Connecting integration...
Connecting to database...

```

Thank you for your help
